// <auto-generated />
using System;
using Ahmed_Task_2.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ahmed_Task_2.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ahmed_Task_2.Web.Models.ActivityCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ActivityCodes");

                    b.HasData(
                        new
                        {
                            Id = 111,
                            Name = "Cultivation of grains and crops (except for rice), legumes and oilseeds"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Cultivation of rice"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Cultivation of vegetables, melons, roots and tubers"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Cultivation of sugar cane"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Tobacco cultivation"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Growing fibre crops"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Cultivation of other non-perennial crops"
                        },
                        new
                        {
                            Id = 121,
                            Name = "The cultivation of grapefruit"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Growing tropical and subtropical fruits"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Cultivation of citrus fruits"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Cultivation of fruit with stone kernel and from palm trees"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Plant fruit trees and shrubs and other nuts"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Growing of tea"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Cultivation of spices crops, aromatic, medicinal and pharmaceutical drugs"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Cultivation of other perennial crops"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Propagation"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Breeding of cattle and buffalo"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Breeding of horses and mare"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Breeding of camels"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Breeding sheep and goat"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Breeding of pig"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Poultry farming"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Breeding other animals"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Mixed agricultural and animal production"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Support activities for animal production"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Activities in support of animal production"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Post-harvest activities"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Preparing grains for production"
                        });
                });

            modelBuilder.Entity("Ahmed_Task_2.Web.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityCodeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateIssued")
                        .HasColumnType("date");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IssuerId")
                        .HasColumnType("int");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityCodeId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.HasIndex("IssuerId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Ahmed_Task_2.Web.Models.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("DiscountPerUnit")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("NetTotal")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("SalesTotal")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("TotalTaxableFees")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("Ahmed_Task_2.Web.Models.InvoiceParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RegionCity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RegistrationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.ToTable("InvoiceParties");
                });

            modelBuilder.Entity("Ahmed_Task_2.Web.Models.InvoiceTax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<int>("InvoiceLineId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<int>("TaxSubTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TaxTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceLineId");

                    b.HasIndex("TaxSubTypeId");

                    b.HasIndex("TaxTypeId");

                    b.ToTable("InvoiceTaxes");
                });

            modelBuilder.Entity("Ahmed_Task_2.Web.Models.TaxSubType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TaxTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaxTypeId");

                    b.ToTable("TaxSubTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "V001 - Standard VAT Rate",
                            TaxTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "V002 - Zero Rated VAT",
                            TaxTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "V003 - Exempt VAT",
                            TaxTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "TP001 - Local Services",
                            TaxTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "TP002 - Luxury Goods",
                            TaxTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "TF001 - Fixed Service Fee",
                            TaxTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "TF002 - Fixed Product Fee",
                            TaxTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "W001 - Contractors",
                            TaxTypeId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "W002 - Professional Services",
                            TaxTypeId = 4
                        },
                        new
                        {
                            Id = 10,
                            Name = "W003 - Suppliers",
                            TaxTypeId = 4
                        },
                        new
                        {
                            Id = 11,
                            Name = "SP001 - Commercial Contracts",
                            TaxTypeId = 5
                        },
                        new
                        {
                            Id = 12,
                            Name = "SF001 - Fixed Stamp Duty",
                            TaxTypeId = 6
                        },
                        new
                        {
                            Id = 13,
                            Name = "E001 - Cinema",
                            TaxTypeId = 7
                        },
                        new
                        {
                            Id = 14,
                            Name = "E002 - Events",
                            TaxTypeId = 7
                        },
                        new
                        {
                            Id = 15,
                            Name = "R001 - Tourism",
                            TaxTypeId = 8
                        },
                        new
                        {
                            Id = 16,
                            Name = "R002 - Government Services",
                            TaxTypeId = 8
                        },
                        new
                        {
                            Id = 17,
                            Name = "TP003 - Imported Goods",
                            TaxTypeId = 9
                        },
                        new
                        {
                            Id = 18,
                            Name = "M001 - Municipality Services",
                            TaxTypeId = 10
                        },
                        new
                        {
                            Id = 19,
                            Name = "MI001 - Medical Insurance Contribution",
                            TaxTypeId = 11
                        },
                        new
                        {
                            Id = 20,
                            Name = "O001 - Administrative Fee",
                            TaxTypeId = 12
                        },
                        new
                        {
                            Id = 21,
                            Name = "O002 - Processing Fee",
                            TaxTypeId = 12
                        });
                });

            modelBuilder.Entity("Ahmed_Task_2.Web.Models.TaxType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TaxTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T1 - Value added tax"
                        },
                        new
                        {
                            Id = 2,
                            Name = "T2 - Table tax (percentage)"
                        },
                        new
                        {
                            Id = 3,
                            Name = "T3 - Table tax (fixed amount)"
                        },
                        new
                        {
                            Id = 4,
                            Name = "T4 - Withholding tax (WHT)"
                        },
                        new
                        {
                            Id = 5,
                            Name = "T5 - Stamping tax (percentage)"
                        },
                        new
                        {
                            Id = 6,
                            Name = "T6 - Stamping tax (amount)"
                        },
                        new
                        {
                            Id = 7,
                            Name = "T7 - Entertainment tax"
                        },
                        new
                        {
                            Id = 8,
                            Name = "T8 - Resource development fee"
                        },
                        new
                        {
                            Id = 9,
                            Name = "T9 - Table tax (percentage)"
                        },
                        new
                        {
                            Id = 10,
                            Name = "T10 - Municipality fees"
                        },
                        new
                        {
                            Id = 11,
                            Name = "T11 - Medical insurance fee"
                        },
                        new
                        {
                            Id = 12,
                            Name = "T12 - Other fees"
                        });
                });

            modelBuilder.Entity("Ahmed_Task_2.Web.Models.Invoice", b =>
                {
                    b.HasOne("Ahmed_Task_2.Web.Models.ActivityCode", "ActivityCode")
                        .WithMany()
                        .HasForeignKey("ActivityCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ahmed_Task_2.Web.Models.InvoiceParty", "Issuer")
                        .WithMany()
                        .HasForeignKey("IssuerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ahmed_Task_2.Web.Models.InvoiceParty", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivityCode");

                    b.Navigation("Issuer");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("Ahmed_Task_2.Web.Models.InvoiceLine", b =>
                {
                    b.HasOne("Ahmed_Task_2.Web.Models.Invoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ahmed_Task_2.Web.Models.InvoiceTax", b =>
                {
                    b.HasOne("Ahmed_Task_2.Web.Models.InvoiceLine", "InvoiceLine")
                        .WithMany("Taxes")
                        .HasForeignKey("InvoiceLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ahmed_Task_2.Web.Models.TaxSubType", "TaxSubType")
                        .WithMany()
                        .HasForeignKey("TaxSubTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ahmed_Task_2.Web.Models.TaxType", "TaxType")
                        .WithMany()
                        .HasForeignKey("TaxTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvoiceLine");

                    b.Navigation("TaxSubType");

                    b.Navigation("TaxType");
                });

            modelBuilder.Entity("Ahmed_Task_2.Web.Models.TaxSubType", b =>
                {
                    b.HasOne("Ahmed_Task_2.Web.Models.TaxType", "TaxType")
                        .WithMany()
                        .HasForeignKey("TaxTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxType");
                });

            modelBuilder.Entity("Ahmed_Task_2.Web.Models.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Ahmed_Task_2.Web.Models.InvoiceLine", b =>
                {
                    b.Navigation("Taxes");
                });
#pragma warning restore 612, 618
        }
    }
}
